### ISSUE TITLE
[Bug] ArgumentException An item with the same key has already been added

### ISSUE THREAD

**Issue by grozeille** [OpenWrap/openwrap#102]
C:\Dev\src\Spring.Demo\Spring.Demo>o.exe add-wrap nhibernate
The OpenWrap shell is not installed on this machine. Do you want to:
(i) install the shell and make it available on the path?
(c) use the current executable location and make it available on the path?
(n) do nothing?
i
Downloading http://wraps.openwrap.org/index.wraplist [....................]
Downloading http://wraps.openwrap.org/openwrap-1.0.0.20507228.wrap [............]
Downloading http://wraps.openwrap.org/openfilesystem-1.0.0.19074013.wrap [.............]
Downloading http://wraps.openwrap.org/sharpziplib-0.85.5.452.wrap [...........]
..# OpenWrap v1.0.0.0 ['C:\Users\mathias\AppData\Local\openwrap\wraps_cache\openwrap-1.0.0.20507228\bin-net35\OpenWrap.dll']
OpenWrap could not be started.
Une exception a été levée par la cible d'un appel.
System.Reflection.TargetInvocationException: Une exception a été levée par la cible d'un appel. ---> System.ArgumentException: Un élément avec la même clé a déjà été ajouté.
   à System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   à System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   à System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   à System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   à OpenWrap.Repositories.CommandExportBuilder.ProcessExports(IEnumerable`1 exports, ExecutionEnvironment environment) dans c:\src\openwrap\src\OpenWrap\Repositories\CommandExportBuilder.cs:ligne 27
   à OpenWrap.Repositories.UncompressedPackage.GetExport(String exportName, ExecutionEnvironment environment) dans c:\src\openwrap\src\OpenWrap\Repositories\UncompressedPackage.cs:ligne 103
   à OpenWrap.Repositories.PackageResolver.<>c__DisplayClassa`1.<GetExports>b__9(IPackage x) dans c:\src\openwrap\src\OpenWrap\Repositories\PackageResolver.cs:ligne 22
   à System.Linq.Enumerable.<>c__DisplayClass12`3.<CombineSelectors>b__11(TSource x)
   à System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   à System.Linq.Enumerable.<OfTypeIterator>d__a3`1.MoveNext()
   à System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   à System.Linq.Enumerable.<OfTypeIterator>d__a3`1.MoveNext()
   à System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   à System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   à System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   à OpenWrap.EnvironmentExtensions.Commands(IEnvironment environment) dans c:\src\openwrap\src\OpenWrap\ConsoleRunner.cs:ligne 178
   à OpenWrap.ConsoleRunner.Main(String[] args) dans c:\src\openwrap\src\OpenWrap\ConsoleRunner.cs:ligne 38
   --- Fin de la trace de la pile d'exception interne ---
   à System.RuntimeMethodHandle._InvokeMethodFast(Object target, Object[] arguments, SignatureStruct& sig, MethodAttributes methodAttributes, RuntimeTypeHandle typeOwner)
   à System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture, Boolean skipVisibilityChecks)
   à System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   à OpenWrap.BootstrapRunner.ExecuteEntryPoint(String[] args, Assembly entryPointAssembly)
   à OpenWrap.BootstrapRunner.Run(String[] args)

**Comment by serialseb** [comment]
Fixed in latest dependency resolvers.
