### ISSUE TITLE
Invalid path created in csproj when using "o init-wrap -all"

### ISSUE THREAD

**Issue by SteveDunn** [OpenWrap/openwrap#104]
Steps to reproduce
1. Create a class library project named Calculator so that you end up with c:\temp\calculator\calculator\calculator.csproj
2. Do 'o init-wrap -all'

OW modifies the .csproj file but puts too many '..' s in the path.  The .csproj file reads:
<Import Project="..\..\wraps\openwrap\build\OpenWrap.CSharp.targets" />

Which causes the following error when reloading in VS:
C:\temp\Calculator\Calculator\Calculator.csproj(45,3): The imported project "C:\temp\wraps\openwrap\build\OpenWrap.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk."

OW version 1.0.0.44 (10th November 2010)

**Comment by serialseb** [comment]
Can you confirm:
- have you done an init-wrap to generate your wrapdesc?
- where is the wrapdesc file in the hierarchy?
- what's the folder structure and why do you not have a src folder?

**Comment by SteveDunn** [comment]
1. Yes
2. Calculator2.wrapdesc in in c:\temp\calculator
3. I do have a src folder.   Structure is:
   <pre>
   C:\temp>tree Calculator
   Folder PATH listing
   Volume serial number is 3C0E-3A4E
   C:\TEMP\CALCULATOR
   +---Calculator
   ¦   +---bin
   ¦   ¦   +---Debug
   ¦   +---obj
   ¦   ¦   +---Debug
   ¦   ¦       +---TempPE
   ¦   +---Properties
   +---src
   +---wraps
   +---openwrap
   ¦   +---bin-net35
   ¦   +---build
   ¦   +---commands
   ¦   +---tests
   +---_cache
       +---openwrap-1.0.0.20507228
           +---bin-net35
           +---build
           +---commands
           +---tests
   </pre>

**Comment by serialseb** [comment]
that's because your calculator project should be in the src folder.

There's already a bug entry to detect the location of the descriptor for each project being patched, but i'm leaving this bug open as a project not in /src should not have been updated.

**Comment by SteveDunn** [comment]
With 'ya - thanks. One of my questions I had stored up for you was 'what's the purpose of the src folder'.  Ta.

**Comment by serialseb** [comment]
We do have a todo in the code for this specific problem and are looking at fixing this, there's a tiny bit of code to put in OFS to support relative paths that we've scheduled for very very soon :)

**Comment by serialseb** [comment]
Detects the correct relative path for MSBuild import. Closed by ac672b0593fb1626e1693672068c8b92cf3ff75c
