### ISSUE TITLE
Configurable anchoring behavior for source control systems not supporting links (svn)

### ISSUE THREAD

**Issue by serialseb** [OpenWrap/openwrap#105]
There are reports that the junction used to link anchored packages is preventing the folder from being checked-in with svn, on both XP and Vista/7.

To account for this, we should add an entry in the descriptor that lets the system use folder copies as opposed to junctions, something along the lines of 'Anchoring-Behaviour: [junction|copy]'

**Comment by SteveDunn** [comment]
Yes, please fix this - it's the only thing that's stopping me from using OW.
How about a o.exe.lnk that points to the o.exe in the respective folder?  Daniel says that this won't work on linux though...

**Comment by serialseb** [comment]
Implemented.
