### ISSUE TITLE
build-wrap: Support for configurations (debug/release/etc)

### ISSUE THREAD

**Issue by scottlittlewood** [OpenWrap/openwrap#106]
I was trying to build a sample project to investigate OpenWrap and upon issueing o build-wrap I noticed that it was building the Debug configuration, the value that was specified in the .csproj of my application.

Maybe it should be possible to specify which configuration you want to build either via the commandline or in the wrapdesc?

**Comment by flq** [comment]
would this be something to specify in wrapdesc's "build" ?

**Comment by flq** [comment]
I am beginning to wonder whether there should be some mechanism in place to partially expose msbuild in the wrapdesc. Consider e.g. that I've seen a number of WPF projects where the code uses compiler flags to decide whether it is compiled for silverlight or not. If you want to support e.g. SL then it'd be great for a developer to state the SILVERLIGHT flag for the SL profile.

**Comment by serialseb** [comment]
That's already in place.`#if __OR_PROFILE_sl30__ || __OR_PROFILE_sl40__`. See the wiki documentation.
