### ISSUE TITLE
Types Defined in multiple assemblies

### ISSUE THREAD

**Issue by scottlittlewood** [OpenWrap/openwrap#116]
When adding the newtonsoft.json wrap the resolver doesn't appear to prefer the net-35 assembly over the net-20 as such the following error is produced by VisualStudio and when issuing o build-wrap on MySampleProject

Error   11  The type 'Newtonsoft.Json.JsonSerializer' exists in both 'c:\git\MySampleProject\wraps_cache\Newtonsoft.Json-3.5.8\bin-net35\Newtonsoft.Json.dll' and 'c:\git\MySampleProject\wraps_cache\Newtonsoft.Json-3.5.8\bin-net20\Newtonsoft.Json.Net20.dll'  C:\git\MySampleProject\src\MySampleProject.Frontend.Web\Codec\NewtonsoftJsonCodec.cs    19  31  MySampleProject.Frontend.Web

**Comment by serialseb** [comment]
Problem from json.net, the assemblies should be named the same.

**Comment by serialseb** [comment]
Tracked as #198
