### ISSUE TITLE
On Windows Server 2003, the myproject\wraps\openwrap\build directory is not accessible

### ISSUE THREAD

**Issue by robertreppel** [OpenWrap/openwrap#149]
This problem does not occur on Windows 7 and XP Professional. 

How to reproduce:
- Run 'o init-wrap myproject'.
- cd to 'myproject\wraps\openwrap\build

Result:
- 'The filename, directory name, or volume label syntax is incorrect.'

**Comment by serialseb** [comment]
Problem comes from server 2003 having some issues with junctions. The problem also happens on non-ntfs drives. Current workaround is to simply deactivate symlinks. More long term solution is to auto-detect if a specific path supports junctions or not, which should be exposed in OFS and then used by OW. Assigning to future as it's low priority.

**Comment by serialseb** [comment]
As the default is now to not use symlinks, closing as resolved.
