### ISSUE TITLE
Out-of-the-box experience

### ISSUE THREAD

**Issue by SteveDunn** [OpenWrap/openwrap#180]
The OOB experience is important.  It would be nice if o.exe didn't report an error when it is run for the very first time.  Here's my experience (just now, on a new machine)
1. Go to OpenWrap.org
2. Download o.exe
3. Run it - it downloads stuff
4. I get an error because I've run it from my \downloads folder and not my projects folder.

Perhaps there could be a flag so that if it was just installed, it won't try and look for any project folders...

**Comment by serialseb** [comment]
Those error messages have been removed in OpenWrap 1.1, and the ones from the shell were removed in the released version. Problem is showing up because the 1.0 packages have that message already.
