### ISSUE TITLE
1.0.0 branch - open sln, crashes Visual Studio

### ISSUE THREAD

**Issue by haf** [OpenWrap/openwrap#184]
I can't work from a 'stable' branch if I want to add support for command line versioning. VS2010 Ultimate SP1.

**Comment by serialseb** [comment]
Need more data as to what "Crashes Visual Studio" means.

Please start VS, attach a debugger (.net 4.0) and open the solution, and provide the debug output.

**Comment by haf** [comment]
I tried to reproduce this problem but failed to do so. I'm closing the issue.
