### ISSUE TITLE
msbuild fails when path contains spaces

### ISSUE THREAD

**Issue by trullock** [OpenWrap/openwrap#187]
`MSBUILD : error MSB1008: Only one project can be specified.`

looks like the answer: http://stackoverflow.com/questions/1057043/how-do-i-have-spaces-in-a-msbuild-webprojectoutputdir

**Comment by serialseb** [comment]
Pretty sure this has been fixed when we switched to response files for msbuild. Which version of OpenWrap is that on?

**Comment by serialseb** [comment]
Closing as no regression reported
