### ISSUE TITLE
Support ReSharper 6

### ISSUE THREAD

**Issue by serialseb** [OpenWrap/openwrap#224]

**Comment by trullock** [comment]
hows this going, anything i can do to help? really need this a.s.a.p.

**Comment by Dfg5** [comment]
The same here. Is there some way we can help?

**Comment by serialseb** [comment]
There should be some code published by the end of the week, then all the testing / coding help you can provide will be more than appreciated :)

-----Original Message-----

**Comment by Dfg5** [comment]
Excellent. I will get it for testing. Thank you.

**Comment by DominicFinn** [comment]
Just checking to see if there is anything testable on this yet? :-) :-) :-)

**Comment by serialseb** [comment]
Due to riots this has Bren taking more time than planned

**Comment by Dfg5** [comment]
any news?
