### ISSUE TITLE
Clear openwrap installation tries to download nuked version of sharpziplib package

### ISSUE THREAD

**Issue by Dfg5** [OpenWrap/openwrap#232]
1. Downloaded new openwrap installer. Cleaned openwrap folder on Local Settings.
2. Started installer with proxy parameter: o.exe -ProxyHref http://proxy.de.db.com:8080

Using proxy at http://proxy.de.db.com:8080/ using default credentials.
Downloading http://wraps.openwrap.org/index.wraplist [..........]
Using proxy at http://proxy.de.db.com:8080/ using default credentials.
Downloading http://wraps.openwrap.org/openfilesystem-1.0.0.61263243.wrap [..........]
Using proxy at http://proxy.de.db.com:8080/ using default credentials.
Downloading http://wraps.openwrap.org/openwrap-1.0.0.63365789.wrap [..........]
Using proxy at http://proxy.de.db.com:8080/ using default credentials.
Downloading http://wraps.openwrap.org/sharpziplib-0.85.5.452.wrap [..........]
Using proxy at http://proxy.de.db.com:8080/ using default credentials.
Downloading http://wraps.openwrap.org/tdnet-framework-2.0.0.48555719.wrap [..........]
Using proxy at http://proxy.de.db.com:8080/ using default credentials.
Downloading http://wraps.openwrap.org/SharpZipLib-0.86.0.wrap []
# OpenWrap Shell could not start.

Could not find OpenWrap assemblies in either current project or system repository.
System.EntryPointNotFoundException: Could not find OpenWrap assemblies in either current project or system repository.
   at OpenWrap.BootstrapRunner.Run(String[] args)

It fails to download 0.86 version of sharpziplib, but downloaded nuked version 0.85.5.452.

Snippet from 
http://wraps.openwrap.org/index.wraplist

<wrap name="sharpziplib" version="0.85.5.452" nuked="true">
<link rel="package" href="sharpziplib-0.85.5.452.wrap"/>
</wrap>
....
<wrap name="SharpZipLib" version="0.86.0">
<link rel="package" href="SharpZipLib-0.86.0.wrap"/>
</wrap>

After that openwrap doesn't work until I manually remove folder of SharpZipLib-0.86 from cache.

**Comment by serialseb** [comment]
Fixed in version 2.0 of the openwrap shell, available on openwrap.org
