### ISSUE TITLE
resource files not copied in wrap

### ISSUE THREAD

**Issue by rvdginste** [OpenWrap/openwrap#268]
I am using the beta repository (http://wraps.openwrap.org/beta/) for both projects and system.

I'm trying to build a wrap from a project that includes translated resources. However, this does not seem to work as intended.

I see the following problems:
1. building project in: ../../scratch/bin/myproj-bla-bla/   (yup, copied from openwrap)

resources dll compiled in ../../scratch/bin/myproj-bla-bla/nl/resources.dll
result: resources dll is not included in generated wrap
1. building project in: bin/Debug/

resources dll placed in bin/Debug/nl/resources.dll
result: resources dll is included in generated wrap, in bin-net35/bin/Debug/nl/resources.dll (not the correct location)

**Comment by serialseb** [comment]
This is in process of being solved

**Comment by serialseb** [comment]
new build engine fixes that problem, please reopen if the problem persists.
