### ISSUE TITLE
Missing o.exe from github downloads

### ISSUE THREAD

**Issue by haf** [OpenWrap/openwrap#294]
No download listed.

**Comment by serialseb** [comment]
o.exe is downaloadable from www.openwrap.org, not the github site. Is that an issue?

**Comment by haf** [comment]
I'm trying to get hold of the latest version... What the .org site gives is version `openwrap-1.0.2.86964541`

**Comment by serialseb** [comment]
See for example https://projects.peopleware.be/confluence/display/PPWCODE/Install+OpenWrap+2.x to install the 2.0 version of OpenWrap, it's not released on the main feed.

## 

Seb

**Comment by serialseb** [comment]
2.0.3 release on the main feed removes that problem.
