### ISSUE TITLE
Trying to get openwrap/symbolsource to work

### ISSUE THREAD

**Issue by haf** [OpenWrap/openwrap#298]
I'm following this guide:
http://www.symbolsource.org/Public/Blog/View/32

Running:

`o.exe add-remote -name itsawrap -href http://openwrap.gw.symbolsource.org/Public/Private.haf.itsawrap -user haf -pwd lkm9032`

gives this error:

`Command input 'user' wasn't recognized`

I then try to see what command-parameter's the command accepts:

`o get-help add-remote`, producing:

```
# OpenWrap Shell 2.0.0.10
# Copyright © naughtyProd Limited 2009-2011
# Using C:\Users\xyz\AppData\Local\openwrap\wraps\_cache\openwrap-1.0.2.86964541\bin-net35\OpenWrap.dll (1.0.0.0)


List of available commands
--------------------------

Usage:
  o {verb}-{noun} <command-arguments>

remote
  add: Adds a remote repository.
  add: Adds a remote repository.


For detailed help on a particular command, run:
  o get-help {verb}-{noun}
```
1. I'm trying to get detailed help - yet it's telling me that I should try to get detailed help.
2. I have no hints as to how I get the list of possible command-parameters.
3. I have tried updating openwrap itself, but that doesn't seem to make a difference, even after adding `http://wraps.openwrap.org/beta`.

**Comment by serialseb** [comment]
You're using 1.0 and not 2.0 so -user is not supported.

## 

Seb

---

From: Henrik Feldt [reply@reply.github.com]
Sent: 10 January 2012 14:58
To: Sebastien Lambla
Subject: [openwrap] Trying to get openwrap/symbolsource to work (#298)

I'm following this guide:
http://www.symbolsource.org/Public/Blog/View/32

Running:

`o.exe add-remote -name itsawrap -href http://openwrap.gw.symbolsource.org/Public/Private.haf.itsawrap -user haf -pwd lkm9032`

gives this error:

`Command input 'user' wasn't recognized`

I then try to see what command-parameter's the command accepts:

`o get-help add-remote`, producing:

```
# OpenWrap Shell 2.0.0.10
# Copyright © naughtyProd Limited 2009-2011
# Using C:\Users\xyz\AppData\Local\openwrap\wraps\_cache\openwrap-1.0.2.86964541\bin-net35\OpenWrap.dll (1.0.0.0)


List of available commands
--------------------------

Usage:
  o {verb}-{noun} <command-arguments>

remote
  add: Adds a remote repository.
  add: Adds a remote repository.


For detailed help on a particular command, run:
  o get-help {verb}-{noun}
```
1. I'm trying to get detailed help - yet it's telling me that I should try to get detailed help.
2. I have no hints as to how I get the list of possible command-parameters.
3. I have tried updating openwrap itself, but that doesn't seem to make a difference, even after adding `http://wraps.openwrap.org/beta`.

---

Reply to this email directly or view it on GitHub:
https://github.com/openrasta/openwrap/issues/298

**Comment by haf** [comment]
I know. That's why I'm trying to update to 2.0, but as I wrote, I can't update to 2.0.

**

Of course, I can build the solution code itself, but the problem is still that I can't migrate to the beta, even with the guidance here: https://projects.peopleware.be/confluence/display/PPWCODE/Install+OpenWrap+2.x

**Comment by serialseb** [comment]
In OpenWrap 1.0 you should "remote add http://wraps.openwrap.org/beta/", the trailing slash is important.

**Comment by serialseb** [comment]
Beta is being moved to the main feed, so the problem goes away. Support for 1.0 is being dropped.
