### ISSUE TITLE
Nuget-pieces of wiki are wrong

### ISSUE THREAD

**Issue by haf** [OpenWrap/openwrap#299]
Trying to add the nuget.

Getting "The address 'nuget://packages.nuget.org/v1/FeedService.svc/Packages' was not recognized as a known repository type."

I've updated the wiki to

`o add-remote nuget`

Verifying:

`o list-remote -detailed` contains nuget.

This issue can be closed.

**Comment by haf** [comment]
Wiki updated.

**Comment by drozzy** [comment]
The command still doesn't work. Executing "o add-remote nuget" produces the error: "Missing values for the following command inputs: Href"
