### ISSUE TITLE
Error on update-wrap: cannot publish package as file already exists.

### ISSUE THREAD

**Issue by rvdginste** [OpenWrap/openwrap#303]
I built master after commit a34e23b779c3772c84c4107fd2c39bedd85f6344

I updated a couple of projects to use this new openwrap build. But as soon as those projects use it, any "o update-wrap" call fails with an exception. It seems like update-wrap wants to overwrite the existing openwrap wrap in the projects "wraps" folder.

The exception is thrown in FolderRepository, line 265 (PackageStorage.Publish).

**Comment by serialseb** [comment]
I would not recommend Building from master at the moment, some issues seem to have crept in. The semver build will be in today, that's a much better base to be working from. 

## 

Sebastien Lambla

**Comment by serialseb** [comment]
Don't think this happens with the semver build anymore. Closing as wontfix. Reopen if the issue persists on those builds.
