### ISSUE TITLE
o -shellinstall no longer recognised after upgrade to v2.x ?

### ISSUE THREAD

**Issue by petemounce** [OpenWrap/openwrap#306]
- I have o.exe in a directory
- cd there
- o.exe -shellInstall none add-remote openwrap-beta http://wraps.openwrap.org/beta/
  - succeeds
- o.exe -shellInstall none update-wrap openwrap -system
  - succeeds
- o.exe -shellInstall none add-remote openwrap-beta http://wraps.openwrap.org/beta/
  - fails with

> # OpenWrap Shell 2.0.0.10
> # Copyright c naughtyProd Limited 2009-2011
> # Using C:\Users\peter.mounce\AppData\Local\openwrap\wraps_cache\OpenWrap-2.0.2.97970098\bin-net35\OpenWrap.dll (2.0.0.1)
> The term '-shellInstall' is not a recognized command or alias. Check the spelling or enter 'get-help' to get a list of available commands.

See https://gist.github.com/1723563 for full output

**Comment by serialseb** [comment]
Moving to the openwrap-shell project, https://github.com/openrasta/openwrap-shell/issues/25

**Comment by serialseb** [comment]
Found the issue to be in the command parser, not in the shell, so reopening here and closing openrasta/openwrap-shell#25
