### ISSUE TITLE
Can't build the current trunk on Mono

### ISSUE THREAD

**Issue by konrad-kruczynski** [OpenWrap/openwrap#320]
I did a checkout of 5d1375456fe75aa753c3bd9d851a6fc2363961e5 and run xbuild in build directory. It was building up to some point but then failed. The complete log is available here: http://pastebin.com/66XDnL6N

**Comment by serialseb** [comment]
OpenWrap will not build on mono due to bugs in their compiler, so for now you'll have to use binaries for your projects. If someone wants, they could contact mono to let them know and get mcs fixed. 

## 

Sebastien Lambla

**Comment by konrad-kruczynski** [comment]
Thank you for your feedback. I will post an issue on Mono's bugzilla and will report it here.

**Comment by konrad-kruczynski** [comment]
The issue is reported here:
https://bugzilla.xamarin.com/show_bug.cgi?id=5342

**Comment by konrad-kruczynski** [comment]
This issue can be closed because of https://github.com/openrasta/openwrap/pull/322
