### ISSUE TITLE
OpenWrap shell weirdness, downloading existing packages

### ISSUE THREAD

**Issue by rvdginste** [OpenWrap/openwrap#328]
OpenWrap shell seems to act weird and tries to download packages that are already in it's system repostory.
It seems to think the root of the system repo is: ...\local\openwrap\ instead of ...\local\openwrap\wraps, since it also creates an "_cache" folder under ...\local\openwrap.

**Comment by serialseb** [comment]
Which version of the shell?

## 

Seb

**Comment by rvdginste** [comment]
Master of openwrap-shell, and master of openwrap.

**Comment by serialseb** [comment]
Thought those were solved. May have missed some preloaded updates, will check tonight where we are

## 

Seb

**Comment by rvdginste** [comment]
Ok... the fix seems to work for me, but still didn't get to do a big test (I wanna run all our openwrap packages through the new version). I hope to do more elaborate tests this weekend.

**Comment by serialseb** [comment]
Fixed in openrasta/openwrap@f2469c13b105353848300b063b9a6c7b3d584aec
