### ISSUE TITLE
Support authentication when publishing to remote repositories

### ISSUE THREAD

**Issue by serialseb** [OpenWrap/openwrap#37]

**Comment by flq** [comment]
OK, I think I should be able to do this.
What do you think? Right now I am favouring to add "User" and "Password" parameters to the add-remote command and letting it trickle through from there, instead of doing it in the "add-wrap" command. Pwd would be saved encrypted of course, but it is also user local anyway...

Delegate! :-)

**Comment by serialseb** [comment]
Actually you are correct, any remote repository access could be password protected. We'd have one of three choices. First is username and pasasword on all commands that take a remote, second would be to persist in config the username and password, encrypted with the machine key, third one would be for platforms that support it to leverage the OS apis for that (aka keychain on macos, DPAPI on win32 etc).

What do you reckon?

**Comment by flq** [comment]
Personally I'd favour the second option for now, as a kind of lowest common denominator thing that would allow you to represent a protected http repository, or network share that requires some uid/pwd combination. Levaraging OS APIs would require more research on my part and is maybe not a necessary step towards v1?..if that's cool by you I can get going on this throughout the coming week.

btw, is this something your current openwrap rep supports, publish access when you have usr/pwd?

**Comment by serialseb** [comment]
we support 3 kinds of remote repositories, UNC paths, Http-based openwrap ones and NuGet. The first two support publishing out of the box (the former through windows authentication, the latter through http digest). NuGet is not supported for publishing.

I think the first thing to do would be the username and password, then move on to record login info per repository.

**Comment by flq** [comment]
I am afraid I don't understand your last sentence...would you want uid/pwd params on publish-wrap, nuke-wrap? that would mean that the credentials need to enter where you interface from commands -> package repository. When we specify uid/pwd when adding a remote repository, one can leave the wrap commands untouched...

**Comment by serialseb** [comment]
yes, quite, but it's important to have them on those commands, for example in teamcity scenarios where you don't want to go login on the server to register passwords.

It's also common that you may want to publish under a different username/password than your regular one.

by doing the username and password command inputs first, we start with the scenario that works in all circumstances, and then we add the configuration option for remotes that are configured locally.

Note that the -remote parameter can take a name or a URI, so the repository may not be in config at all.

**Comment by flq** [comment]
OK Then. The test suite runs fine, so all's good. I am uncertain how I'd do a bog standard debugging session, though, so I may have to come back for that. I'll checkin regularly to my fork.

**Comment by serialseb** [comment]
Wonderfull. Do you want me to have a look now or should i wait till you do a pull request?

**Comment by flq** [comment]
Haha, there isn't much to see yet, but I tell you my plan for the coming days: Define some credential value object, get it filled with parameters to the publish wrap command, get it to the system through ISupportPublishing. I could do a change to the publish meth, maybe having a crednetial instance that works as "no credentials" and an overload and then end up in the different repository implementations and do necessary credential setting etc. etc.
When there's something to see, I'll write here.

**Comment by serialseb** [comment]
Thing is, some private remote repositories may have username/password associated to them too, so ISupportPublishing won't do.

I think it'd be better to have an ISupportImpersonation or ISupportCredentials, with a method along the lines of IDisposable Impersonate(Credentials credentials)?

We're trying to keep interfaces as small as possible. This is especially important as we're very close to freezing them for our v1, we don't want breakage if we can avoid it :)

**Comment by flq** [comment]
In which case all repositories that support it would implement that interface, I suppose...those that don't, don't. Sounds understandable :)

**Comment by serialseb** [comment]
Thats the rationale yes, if you support the functioanlity, you declare it with the method. We don't have CanXxx methods because we just ignore calls when things are not enabled. For example, if a repository type supports ISupportAnchoring and we don't enable it on an instance, we return nothing, stay silent as death. :)

**Comment by flq** [comment]
Hi seb :)
just getting into the nitty gritty: In publish wrap you have a check running to ensure the sanity of input. What I wanted to do is that when usr/pwd is provided, but repository doesn't support auth, only a warning is output. Your current SequenceBuilder.Or implementation does not support such a scenario, as it ends the chain when "Or" yields. What I could use in that situation is a side-effecting "Or", e.g. called "Passthrough" that yields but does not stop the sequence. This would actually allow to break down a big check method into several smaller ones. I think I could implement it without grand changes and SequenceBuilder is implicitly _very_ well tested. What do you think ?

**Comment by serialseb** [comment]
I'd say that the sequence builder should only stop when an error was yielded instead of whenever anything is yielded?

I think that wouldn't break anything and would work better. Maybe we should rename this stuff by having a ValidateInputs and Process abstract methods on the base class, where execution stops if ValidateInputs yields an error?
