### ISSUE TITLE
Support edge versions of packages

### ISSUE THREAD

**Issue by serialseb** [OpenWrap/openwrap#4]
Packages are all included in repositories. Some packages must be marked as "edge" packages, and only usable when such a tag is applied to the dependency import.

It would be nice to have this as a generalized mechanism along the lines of the namespace support in C#.

For example:
    nhibernate-3.0.0.1.wrap
    namespace: edge

and in your consumer:
     depends: edge/nhibernate

and the command-line
   add-wrap nhibernate -namespace edge

This would also allow complete distributed categorization of content, letting you only import pacakges you're happy to search for.

**Comment by jthigpen** [comment]
Is there only one "edge" package per... package? ie, if I do add-wrap nhibernate -namespace edge would is that unique at all times? namespace seems confusing. I would better understand edge being an option to -version that add-wrap understands.

add-wrap nhibernate -version edge

Is edge common nomenclature? it doesn't really imply "super beta pre-release" to me, but I might just be out of touch with the domain.

**Comment by serialseb** [comment]
nope, you can have as many edge packages as you want. Typically, nhibernate 2.1 beta will still be present while 2.1 release and 3.0 beta will all be available.

The reason for calling it namespace is to seggregate those versions that are not part of the "general" feed without requiring a separate feed. This also leaves the versioning intact, which is important, otherwise you'd end up with your 2.1 beta being updated to 3.0 beta next time you do an update.

**Comment by jthigpen** [comment]
gotcha, that makes sense. What other namespaces besides edge do you envision?

add-wrap nhibernate -version 3.0 -edge

**Comment by serialseb** [comment]
That's a good question. By providing edge for beta quality, one could quite easily see that namespaces could be used for 'experimental', alpha, beta, whatever the package author decides to use as its namespace for the version he publishes and don't want exposed openly. Or you may want the beta versions (edge) to be separate from the CI versions, this provides a convenient way to split the two.

**Comment by jthigpen** [comment]
I think it's a useful feature, but I question whether or not it's gold plating, i.e., is there a use case for a generalized namespace construct, or is the majority of user demand going to be for 'stable' vs. 'edge'. I'm not convinced either way, I honestly don't know. 

I would also carefully consider the choice of 'namespace' as the feature name:

add-wrap nhibernate -version 3.0 -namespace edge
add-wrap nhibernate -version 3.0 -namespace custom_build_for_bobby
add-wrap nhibernate -version 3.0 -namespace stable

vs.

add-wrap nhibernate -version 3.0 -release edge
add-wrap nhibernate -version 3.0 -release custom_build_for_bobby
add-wrap nhibernate -version 3.0 -release stable

**Comment by serialseb** [comment]
release sounds interesting, but i'm not sure it conveys what the feature actually does. From a consumer perspective, would having a simple -edge solve the 80%, with the namespace concept only needed for package builders and more advanced users?

**Comment by jthigpen** [comment]
FWIW, As a package consumer, I have only ever been interested in 2 scenarios:
1. "Give me the bits that work" (stable)
2. "Give me the newest bits with that hot new feature/bugfix I need." (edge)

**Comment by serialseb** [comment]
so would you say that add-wrap nhibernate -edge would solve that requirement?

**Comment by flq** [comment]
what about "alpha/beta/release" nomenclature? E.g. NHibernate will usually tag its stuff beta. It naturally leads to 3 different settings instead of 2, but that may not make much of a difference

**Comment by serialseb** [comment]
In the case of alpha / beta / release, they would have different package versions (2.0.1, 2.0.2, 2.0.3), but you are correct that adding a namespace identifier to each package through the mechanism I've described would let you have the same version for packages that live in different namespaces without causing collision, so it'd be up to the package maintainers

**Comment by serialseb** [comment]
One additional point: When importing a pacakge in a different namespace, an override needs to exist automatically between the non-namespaced and the namespaced package. Otherwise, there would be no way for the system to be able to resolve the edge/nhibernate package when a request exists for nhibernate.
