### ISSUE TITLE
Replace the Version class use by a custom PackageVersion type

### ISSUE THREAD

**Issue by serialseb** [OpenWrap/openwrap#48]
The Version class does not support wildcard, which we use. Other package formats (such as semantic package versioning) support tagged versions (1.0.0beta) which is something we may consider in the future.

Replacing the code with a custom VersionDeclaration type with proper ToString, operator overloading and equality would make the code much better and provide for future extensibility more easily.

**Comment by andrewdavey** [comment]
How do you want to do tagging? A string "Tag" property in addition to the others?
How should that affect ordering of versions?

**Comment by serialseb** [comment]
Don't think tagging relates to that part of the code
