### ISSUE TITLE
wrap add: descriptor updated after package add is successful

### ISSUE THREAD

**Issue by serialseb** [OpenWrap/openwrap#68]

**Comment by andrewdavey** [comment]
Is this as easy as moving
    if (ShouldUpdateDescriptor)
        yield return UpdateDescriptor();
to the end of the ExecuteCore() method?

**Comment by serialseb** [comment]
saves descriptor after successful installation of a package. Closed by 7ced225203b5e6444e5319f215b5143bbf68861d
