### ISSUE TITLE
Files build provider

### ISSUE THREAD

**Issue by serialseb** [OpenWrap/openwrap#71]

**Comment by andrewdavey** [comment]
Can you elaborate on what this feature should do?

**Comment by serialseb** [comment]
Build provider called files, that lets you copy certain files:

build: files; file=path/to/file.dll->bin-net20; file=path/to/another/file.dll -> bin-net35

Purpose is to have a way to copy files without getting openwrap to execute the build for you. Why you'd want to do that, I don't know, but some people are a bit strange and like complicated stuff like that. :)

Note that build providers get the file= part automatically assigned to an IEnumerable<string> so it is rather easy

**Comment by serialseb** [comment]
Implemented in SHA1: dbd763b17b1cf8be2be8
