### ISSUE TITLE
Too many files added in the convention-based OpenWrap MSBuild file

### ISSUE THREAD

**Issue by serialseb** [OpenWrap/openwrap#75]
PDBs and XML files are added for all referenced assemblies, including those that are marked as CopyLocal=false. Same happens with PDBs and XML files associted with packages.

Those should be removed.

**Comment by andrewdavey** [comment]
Where should I look in the code to work on this?

**Comment by serialseb** [comment]
msbuild target file

**Comment by serialseb** [comment]
To be exact, referenced assemblies and referenced projects that are not OpenWrap-injected and marked as copylocal=true should be copied alongside whatever files they came with.

Ignored are assemblies that were OpenWrap-injected, irrespective of their copylocal value.

Assemblyes not injected by openwrap and marked copylocal=false should not be copied, neither should their associated files.

The task may require removing the logic from the msbuild file and pushing it into a separate msbuild task, which would be much more testable anyway.

**Comment by serialseb** [comment]
Fixed.
