### ISSUE TITLE
Compilation error in NuPackConverter.cs

### ISSUE THREAD

**Issue by igitur** [OpenWrap/openwrap#90]
I'm trying to build openwrap and I get this error:

Repositories\NuPack\NuPackConverter.cs(130,32): error CS0411: The type arguments for method 'System.Linq.Enumerable.Select<TSource,TResult>(System.Collections.Generic.IEnumerable<TSource>, System.Func<TSource,TResult>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.

**Comment by serialseb** [comment]
Can't repro, not sure what SHA / build this is from.

**Comment by igitur** [comment]
I did a fresh pull from git now. 
I have msbuild v3.5.30729.1

Again, I get this:

CoreResGen:
  No resources are out of date with respect to their source files. Skipping resource generation.
CSC : warning CS1668: Invalid search path 'C:\Program Files\Microsoft SDKs\Windows\v6.0A\lib' specified in 'LIB environment variable' -- 'The system cannot find the path specified. '
ConsoleRunner.cs(152,13): warning CS0162: Unreachable code detected
Repositories\NuPack\NuPackConverter.cs(130,32): error CS0411: The type arguments for method 'System.Linq.Enumerable.Select<TSource,TResult>(System.Collections.Generic.IEnumerable<TSource>, System.Func<TSource,TResult>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.
Dependencies\DependsParser.cs(54,17): warning CS0219: The variable 'consumedArgs' is assigned but its value is never used
Done Building Project "C:\dev\openwrap2\openwrap\src\OpenWrap\OpenWrap.csproj" (default targets) -- FAILED.
Done Building Project "C:\dev\openwrap2\openwrap\src\OpenWrap.Resharper.v450\OpenWrap.Resharper.v450.csproj" (default targets) -- FAILED.

How can I attach the full log?

**Comment by serialseb** [comment]
That was trying to build openwrap with the 3.5 compilers instead of the 4.0 ones, which are required.
