### ISSUE TITLE
"Namespace not found" when trying to create a wrap

### ISSUE THREAD

**Issue by jhollingworth** [OpenWrap/openwrap#94]
I am trying to create a new wrap. If I go into a project I want to turn into a wrap, run "o wrap init" and the "o build wrap" I get a "Namespace not found" error. Whats slightly weird is that all commands (e.g. o get-help) will all return "Namespace not found" if I am in a folder with a .wrapdesc. Is there something I am missing?

**Comment by serialseb** [comment]
fixed, do a pull and update your version

**Comment by jhollingworth** [comment]
Hi, I've got the latest version (updated 1h ago). It is improved from a few hours ago (i.e. I can do "o get-help" from c:\ but not from a folder containing a .wrapdesc. Unless I need to do more that "o wrap build" & "o wrap update"?

**Comment by serialseb** [comment]
update-wrap -project -system. Make sure you got the latest version in both
