### ISSUE TITLE
When resolving dependencies, local repositories should be favoured over remote repositories

### ISSUE THREAD

**Issue by dirv** [OpenWrap/openwrap#95]
Calls to PackageManager.TryResolveDependencies will return dependencies based on the order of repositories passed to it.

I think it should resolve in proximity order (i.e. project, system, remote), by ordering the list of repositories passed to it.

**Comment by serialseb** [comment]
That code is being changed completely around atm. The latest found version should always be privileged when calling TryResolveDependencies, the consumers of that api should be the ones responsible for copying stuff around, and then choose the version that' the closest (which was half of the previous behavior that was changed).

Should have a commit tomorrow with the new dependency levelling thing.

**Comment by serialseb** [comment]
new resolution behavior is in, this should be ok now.
